version: '3'

services:
  registry:
    image: registry:2
    ports:
    - "4000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data
      - ./config.yml:/etc/docker/registry/config.yml
    restart: always
